server {
    listen 80;
    server_name localhost;

    location = /33zzadmin {
        return 301 /33zzadmin/;
    }

    location /33zzadmin/assets/ {
        alias /usr/share/nginx/html/33zzadmin/assets/;
        try_files $uri =404;
    }

    location = /33zzadmin/favicon.svg {
        alias /usr/share/nginx/html/33zzadmin/favicon.svg;
    }

    location = /33zzadmin/icons.svg {
        alias /usr/share/nginx/html/33zzadmin/icons.svg;
    }

    location /33zzadmin/ {
        alias /usr/share/nginx/html/33zzadmin/;
        try_files $uri $uri/ /33zzadmin/index.html;
    }
}
